-- 코드를 입력하세요
SELECT
    INF.REST_ID AS REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM
    REST_INFO AS INF JOIN REST_REVIEW AS REV
ON
    INF.REST_ID = REV.REST_ID
WHERE
    ADDRESS LIKE "서울%"
GROUP BY
    INF.REST_ID
ORDER BY
    SCORE DESC, FAVORITES DESC