-- 코드를 입력하세요
SELECT
    OUTS.ANIMAL_ID AS ANIMAL_ID,
    OUTS.NAME AS NAME
FROM
    ANIMAL_INS AS INS RIGHT OUTER JOIN ANIMAL_OUTS AS OUTS
ON
    INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE
    INS.ANIMAL_ID IS NULL