SELECT
    month(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    CAR_ID
IN
    (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE date(START_DATE) >= '2022-08-01'
        AND date(START_DATE) < '2022-11-01'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
AND date(START_DATE) >= '2022-08-01'
AND date(START_DATE) < '2022-11-01'
GROUP BY CAR_ID, month(START_DATE)
ORDER BY month(START_DATE) ASC, CAR_ID DESC